apiVersion: v1
kind: Service
metadata:
  name: {{ include "evolane.fullname" . }}
  labels:
    app: {{ include "evolane.name" . }}
    chart: {{ include "evolane.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.type }}
  ports:
    - port: 80 
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "evolane.name" . }}
    release: {{ .Release.Name }}
